import Navbar from "./_components/Navbar";
import "./globals.css";
import { Noto_Sans_Mono } from "next/font/google";

const noto = Noto_Sans_Mono({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" webcrx="">
      <body className={`${noto.className} flex flex-col min-h-screen`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
